//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsSpisokTB
    {
        public int Id { get; set; }
        public int id_Рота { get; set; }
        public int Id_Сотрудник { get; set; }
        public int Id_Звания { get; set; }
        public int Id_Роли { get; set; }
    
        public virtual InsRoleTB InsRoleTB { get; set; }
        public virtual InsRotaTB InsRotaTB { get; set; }
        public virtual InsSotrTB InsSotrTB { get; set; }
        public virtual InsZvanieTB InsZvanieTB { get; set; }
    }
}
