//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr691_koyEntities1 : DbContext
    {
        public gr691_koyEntities1()
            : base("name=gr691_koyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InsRasporadokTB> InsRasporadokTBs { get; set; }
        public virtual DbSet<InsRoleTB> InsRoleTBs { get; set; }
        public virtual DbSet<InsRotaTB> InsRotaTBs { get; set; }
        public virtual DbSet<InsSolderTB> InsSolderTBs { get; set; }
        public virtual DbSet<InsSotrTB> InsSotrTBs { get; set; }
        public virtual DbSet<InsSpisokTB> InsSpisokTBs { get; set; }
        public virtual DbSet<InsZvanieTB> InsZvanieTBs { get; set; }
        public virtual DbSet<Vhod_SotrudnicaTB> Vhod_SotrudnicaTB { get; set; }
    }
}
