//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vhod_SotrudnicaTB
    {
        public int ID { get; set; }
        public int Id_Сотрудник { get; set; }
        public int Id_Пароль { get; set; }
    
        public virtual InsSotrTB InsSotrTB { get; set; }
        public virtual InsSotrTB InsSotrTB1 { get; set; }
    }
}
